apiVersion: infra.io.odimra/v1
kind: Odim
metadata:
  name: odim
  namespace: bmc-op
  annotations:
    infra.io/auth: odimauth
spec:
  URL: https://<ip>:<port>
  EventListenerHost: https://<ip>:<port>