apiVersion: v1
kind: Secret
metadata:
  name: odimauth
  namespace: bmc-op
type: BasicAuth/RedfishSessionAuth
data:
  username: <b64_encoded_username>
  password: <b64_encoded_password>

---

apiVersion: infra.io.odimra/v1
kind: Odim
metadata:
  name: odim
  namespace: bmc-op
  annotations:
    infra.io/auth: odimauth
spec:
  URL: https://<ip>:<port>
  EventListenerHost: https://<ip>:<port>