apiVersion: v1
kind: Service
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app: manager
spec:
  ports:
  - nodePort: 32123
    port: 45000
  selector:
    control-plane: controller-manager
    app: manager
  type: NodePort