apiVersion: v1
kind: Secret
metadata:
  name: bmc-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: bmc-secret
type: Opaque
data:
  publicKey: {{ .Values.data.publicKey | b64enc }} 
  privateKey: {{ .Values.data.privateKey | b64enc }}
  eventClientCert: {{ .Values.data.eventClientCert | b64enc }}
  eventClientKey: {{ .Values.data.eventClientKey | b64enc }}
  rootCACert: {{ .Values.data.rootCACert | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: odimauth
  namespace: {{ .Values.namespace }}
type: BasicAuth/RedfishSessionAuth
data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password }}
