kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: operator-log-claim
  namespace: bmc-op
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi