kind: PersistentVolume
apiVersion: v1
metadata:
  name: operator-log
  namespace: bmc-op
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: bmc-op
    name: operator-log-claim
  hostPath:
    path: /var/log/operator_logs