# permissions for end users to view biosschemaregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: biosschemaregistry-viewer-role
rules:
- apiGroups:
  - infra.io.odimra
  resources:
  - biosschemaregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.io.odimra
  resources:
  - biosschemaregistries/status
  verbs:
  - get
