# permissions for end users to view biossettings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: biossetting-viewer-role
rules:
- apiGroups:
  - infra.io.odimra
  resources:
  - biossettings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.io.odimra
  resources:
  - biossettings/status
  verbs:
  - get
