# permissions for end users to edit bootordersettings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bootordersettings-editor-role
rules:
- apiGroups:
  - infra.io.odimra
  resources:
  - bootordersettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.io.odimra
  resources:
  - bootordersettings/status
  verbs:
  - get
