# permissions for end users to edit eventsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eventsubscription-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: server-operator
    app.kubernetes.io/part-of: server-operator
    app.kubernetes.io/managed-by: kustomize
  name: eventsubscription-editor-role
rules:
- apiGroups:
  - infra.io.odimra
  resources:
  - eventsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.io.odimra
  resources:
  - eventsubscriptions/status
  verbs:
  - get
