# permissions for end users to edit odims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odim-editor-role
rules:
- apiGroups:
  - infra.io.odimra
  resources:
  - odims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.io.odimra
  resources:
  - odims/status
  verbs:
  - get
