apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bmc-opleader-election-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bmc-opleader-election-role
subjects:
- kind: ServiceAccount
  name: bmc-opcontroller-manager
  namespace: {{ .Values.namespace }}