reconciliation: Accommodate
eventSubReconciliation: Accommodate
reconcileInterval: 24
logLevel: debug
logFormat: syslog
namespace: bmc-op
image: <operator image path>
username: <plaintext username>
password: <encrypted password>
EventSubscriptionEventTypes:
  - ResourceAdded
  - ResourceRemoved
  - Alert
EventSubscriptionMessageIds:
  - ResourceEvent.1.2.0.ResourceRemoved
  - ResourceEvent.1.2.0.ResourceAdded
  - iLOEvents.3.2.ServerPostDiscoveryComplete
  - iLOEvents.3.2.ServerPostComplete
EventSubscriptionResourceTypes: 
  - ComputerSystems